server.port: 8086

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql:  true
  datasource:
    url: jdbc:mysql://localhost:3306/mp3_player?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: mp3_player_admin
    password: admin